langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-4o-mini
      temperature: 0.7
      timeout: PT3M
      log-requests: false
      log-responses: false
      response-format: json_schema
