langchain4j:
  open-ai:
    chat-model:
      api-key: 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
      model-name: gpt-4o-mini
      temperature: 0.7
      timeout: PT3M
      log-requests: false
      log-responses: false
      response-format: json_schema